### ISSUE TITLE
linux上启动有时候会白屏卡死

### ISSUE THREAD

**Issue by dudes-come** [tnelab/tchapp#29]
如题，可能和标题范围的检测有关

**Comment by dudes-come** [comment]
经过测试是off-screen-rendering-enabled选项导致的，但是去掉这个选项以后标题栏无法拖动

**Comment by esrinzou** [comment]
`  //zmg 2016-12-8

  //for js caption rect

  gint width, height;

  gdk_drawable_get_size(GDK_DRAWABLE(GTK_WINDOW(parent_handle)), &width, &height);

  glarea_->allocation.x=0;

  glarea_->allocation.y=0;

  glarea_->allocation.width=width;

  glarea_->allocation.height=height;  

  //zmg end`
gdk_drawable_get_size有时候会失败，导致width和height采用默认值，这个值非常大，导致内存carsh
修正代码:
`  //zmg 2016-12-8

  //for js caption rect

  glarea_->allocation.x=-1;

  glarea_->allocation.y=-1;

  glarea_->allocation.width=0;

  glarea_->allocation.height=0;  

  //zmg end`
只需给glarea_->allocation随便设置个值，就能解决启动黑屏,js计算标题栏延迟问题
